import * as Joi from 'joi';
export const configValidationSchema = Joi.object({
    PORT: Joi.number().port().default(3000),
    CORS_ORIGIN: Joi.string().default('*'),
    DB_HOST: Joi.string().required(),
    DB_PORT: Joi.number().port().default(5432),
    DB_USER: Joi.string().required(),
    DB_PASS: Joi.string().required(),
    DB_NAME: Joi.string().required(),
    DB_LOGGING: Joi.string().valid('true', 'false').default('false'),
    REDIS_HOST: Joi.string().default('127.0.0.1'),
    REDIS_PORT: Joi.number().port().default(6379),
    REDIS_DB: Joi.number().integer().min(0).default(0),
    REDIS_PASSWORD: Joi.string().allow(''),
    REDIS_URL: Joi.string().allow(''),
    JWT_SECRET: Joi.string().min(12).required(),
    JWT_EXPIRES_IN: Joi.string().default('1d'),
    THROTTLE_TTL: Joi.number().integer().min(1).default(60),
    THROTTLE_LIMIT: Joi.number().integer().min(1).default(100),
    EMAIL_PROVIDER_URL: Joi.string().uri().allow(''),
    EMAIL_PROVIDER_API_KEY: Joi.string().allow(''),
    SMS_PROVIDER_URL: Joi.string().uri().allow(''),
    SMS_PROVIDER_API_KEY: Joi.string().allow(''),
});
